-- ============================================================
-- SUPABASE POSTGRESQL PRODUCTION DATABASE SCHEMA
-- Sabjies Fresh Grocery - Fully Normalized Database
-- ============================================================

-- 1. USERS TABLE
CREATE TABLE IF NOT EXISTS public.users (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  phone TEXT,
  password TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'user',
  addresses JSONB DEFAULT '[]'::jsonb,
  joined_at TIMESTAMPTZ DEFAULT NOW(),
  status TEXT NOT NULL DEFAULT 'Active',
  must_change_password BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_users_email ON public.users(email);
CREATE INDEX IF NOT EXISTS idx_users_phone ON public.users(phone);

-- 2. PRODUCTS TABLE
CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  cat TEXT NOT NULL,
  type TEXT DEFAULT 'organic',
  cp NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
  sp NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
  weight TEXT NOT NULL DEFAULT 'per kg',
  discount TEXT DEFAULT '',
  img TEXT DEFAULT '',
  emoji TEXT DEFAULT '🥬',
  rating NUMERIC(3, 2) DEFAULT 5.0,
  reviews INTEGER DEFAULT 0,
  stock_qty INTEGER NOT NULL DEFAULT 50,
  low_at INTEGER DEFAULT 10,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_products_cat ON public.products(cat);
CREATE INDEX IF NOT EXISTS idx_products_type ON public.products(type);

-- 3. ORDERS TABLE
CREATE TABLE IF NOT EXISTS public.orders (
  id TEXT PRIMARY KEY,
  user_id TEXT REFERENCES public.users(id) ON DELETE SET NULL,
  user_email TEXT NOT NULL,
  user_name TEXT NOT NULL,
  items JSONB NOT NULL DEFAULT '[]'::jsonb,
  subtotal NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
  delivery NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
  discount_applied NUMERIC(10, 2) DEFAULT 0.00,
  coupon_applied TEXT DEFAULT '',
  total NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
  payment TEXT NOT NULL DEFAULT 'COD',
  payment_status TEXT NOT NULL DEFAULT 'Pending',
  utr_number TEXT DEFAULT '',
  payment_screenshot TEXT DEFAULT '',
  status TEXT NOT NULL DEFAULT 'Processing',
  address TEXT NOT NULL,
  phone TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  cancellation_reason TEXT DEFAULT '',
  cancelled_at TIMESTAMPTZ,
  refunded_at TIMESTAMPTZ,
  refund_note TEXT DEFAULT '',
  cashier TEXT DEFAULT 'Online Order'
);

CREATE INDEX IF NOT EXISTS idx_orders_user_id ON public.orders(user_id);
CREATE INDEX IF NOT EXISTS idx_orders_user_email ON public.orders(user_email);
CREATE INDEX IF NOT EXISTS idx_orders_status ON public.orders(status);
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON public.orders(created_at DESC);

-- 4. OFFERS TABLE
CREATE TABLE IF NOT EXISTS public.offers (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title TEXT NOT NULL,
  desc_text TEXT DEFAULT '',
  tag TEXT DEFAULT 'HOT DEAL',
  tag_color TEXT DEFAULT '#f97316',
  img TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. REVIEWS TABLE
CREATE TABLE IF NOT EXISTS public.reviews (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  author_name TEXT NOT NULL,
  location TEXT DEFAULT '',
  rating INTEGER CHECK (rating >= 1 AND rating <= 5) DEFAULT 5,
  body TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. PAYMENT SETTINGS TABLE
CREATE TABLE IF NOT EXISTS public.payment_settings (
  id INTEGER PRIMARY KEY DEFAULT 1,
  business_name TEXT DEFAULT 'Sabjies Fresh Grocery',
  upi_id TEXT DEFAULT 'sabjies.fresh@okhdfcbank',
  qr_code_url TEXT DEFAULT '',
  qr_code_file_name TEXT DEFAULT '',
  qr_code_uploaded BOOLEAN DEFAULT FALSE,
  instructions TEXT DEFAULT '',
  enable_upi BOOLEAN DEFAULT TRUE,
  enable_cod BOOLEAN DEFAULT TRUE,
  auto_approve_upi BOOLEAN DEFAULT FALSE,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. BUSINESS SETTINGS TABLE
CREATE TABLE IF NOT EXISTS public.business_settings (
  id INTEGER PRIMARY KEY DEFAULT 1,
  min_free_delivery NUMERIC(10, 2) DEFAULT 299.00,
  standard_shipping NUMERIC(10, 2) DEFAULT 30.00,
  gst_percentage NUMERIC(5, 2) DEFAULT 5.00,
  operational_hours_start TEXT DEFAULT '09:00 AM',
  operational_hours_end TEXT DEFAULT '09:00 PM',
  is_open BOOLEAN DEFAULT TRUE,
  support_phone TEXT DEFAULT '99203 24172',
  address TEXT DEFAULT 'Ghatkopar East, Mumbai, Maharashtra 400075',
  business_name TEXT DEFAULT 'Sabjies',
  support_email TEXT DEFAULT 'greensabjies@gmail.com',
  website TEXT DEFAULT 'www.sabjies.in',
  gst_number TEXT DEFAULT '',
  fssai_license TEXT DEFAULT '',
  business_registration_number TEXT DEFAULT '',
  enable_ig_banner BOOLEAN DEFAULT TRUE,
  ig_profile_url TEXT DEFAULT 'https://www.instagram.com/sabjies?igsh=MWp6cDQ2NHZtcnE0Zw',
  ig_banner_text TEXT DEFAULT '🎁 Follow us on Instagram for exclusive discount codes.',
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. COUPONS TABLE
CREATE TABLE IF NOT EXISTS public.coupons (
  code TEXT PRIMARY KEY,
  discount NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
  min_order NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
  usage INTEGER NOT NULL DEFAULT 0,
  type TEXT NOT NULL DEFAULT 'flat',
  expiry TEXT DEFAULT '2026-12-31',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. NOTIFICATIONS TABLE
CREATE TABLE IF NOT EXISTS public.notifications (
  id TEXT PRIMARY KEY,
  user_id TEXT REFERENCES public.users(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  type TEXT DEFAULT 'general',
  read BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_notifications_user_id ON public.notifications(user_id);

-- 10. ADDRESSES TABLE
CREATE TABLE IF NOT EXISTS public.addresses (
  id TEXT PRIMARY KEY,
  user_id TEXT REFERENCES public.users(id) ON DELETE CASCADE,
  name TEXT DEFAULT '',
  label TEXT DEFAULT 'Home',
  flat TEXT DEFAULT '',
  street TEXT DEFAULT '',
  area TEXT DEFAULT 'Ghatkopar East',
  pin TEXT DEFAULT '400075',
  city TEXT DEFAULT 'Mumbai',
  state TEXT DEFAULT 'Maharashtra',
  landmark TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_addresses_user_id ON public.addresses(user_id);

-- 11. LOGIN HISTORY TABLE
CREATE TABLE IF NOT EXISTS public.login_history (
  id TEXT PRIMARY KEY,
  user_id TEXT DEFAULT 'unknown',
  identifier TEXT DEFAULT '',
  status TEXT DEFAULT 'Success',
  ip TEXT DEFAULT '',
  user_agent TEXT DEFAULT '',
  timestamp TIMESTAMPTZ DEFAULT NOW()
);

-- 12. PASSWORD RESETS TABLE
CREATE TABLE IF NOT EXISTS public.password_resets (
  id TEXT PRIMARY KEY,
  user_id TEXT REFERENCES public.users(id) ON DELETE CASCADE,
  email TEXT NOT NULL,
  phone TEXT DEFAULT '',
  name TEXT DEFAULT '',
  reason TEXT DEFAULT '',
  status TEXT DEFAULT 'Pending',
  requested_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  approved_at TIMESTAMPTZ,
  approved_by TEXT DEFAULT '',
  admin_notes TEXT DEFAULT '',
  temp_password_hash TEXT DEFAULT '',
  temp_password TEXT DEFAULT '',
  token TEXT DEFAULT '',
  expires_at TIMESTAMPTZ,
  notification_status TEXT DEFAULT 'Pending',
  last_login TEXT DEFAULT '',
  device_info TEXT DEFAULT '',
  ip TEXT DEFAULT '',
  audit_trail JSONB DEFAULT '[]'::jsonb,
  used BOOLEAN DEFAULT FALSE
);

-- 13. SESSIONS TABLE
CREATE TABLE IF NOT EXISTS public.sessions (
  id TEXT PRIMARY KEY,
  user_id TEXT REFERENCES public.users(id) ON DELETE CASCADE,
  token TEXT UNIQUE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  expires_at TIMESTAMPTZ
);

-- 14. REDEMPTION LOGS TABLE
CREATE TABLE IF NOT EXISTS public.redemption_logs (
  id TEXT PRIMARY KEY,
  user_id TEXT REFERENCES public.users(id) ON DELETE SET NULL,
  coupon_code TEXT REFERENCES public.coupons(code) ON DELETE SET NULL,
  order_id TEXT REFERENCES public.orders(id) ON DELETE SET NULL,
  discount_amount NUMERIC(10, 2) DEFAULT 0.00,
  timestamp TIMESTAMPTZ DEFAULT NOW()
);

-- 15. AUDIT LOGS TABLE
CREATE TABLE IF NOT EXISTS public.audit_logs (
  id TEXT PRIMARY KEY,
  action TEXT NOT NULL,
  performed_by TEXT DEFAULT 'system',
  details JSONB DEFAULT '{}'::jsonb,
  timestamp TIMESTAMPTZ DEFAULT NOW()
);

-- 16. CATEGORIES TABLE
CREATE TABLE IF NOT EXISTS public.categories (
  id TEXT PRIMARY KEY,
  label TEXT NOT NULL,
  emoji TEXT DEFAULT '📦',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- DISABLE ROW LEVEL SECURITY FOR ALL TABLES FOR DIRECT API SERVICE ROLE & ANON ACCESS
ALTER TABLE public.users DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.products DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.offers DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.reviews DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.payment_settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.business_settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.coupons DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.addresses DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.login_history DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.password_resets DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.sessions DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.redemption_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories DISABLE ROW LEVEL SECURITY;

-- SEED DEFAULT CATEGORIES
INSERT INTO public.categories (id, label, emoji) VALUES
  ('all', 'All Sabjis', '🛒'),
  ('leafy', 'Leafy Greens', '🥬'),
  ('root', 'Root Veggies', '🥕'),
  ('gourd', 'Gourds & Squash', '🥒'),
  ('herbs', 'Herbs & Seasoning', '🌿'),
  ('organic', 'Certified Organic', '🌱'),
  ('exotic', 'Exotic Veggies', '🥑')
ON CONFLICT (id) DO NOTHING;

